-- separate script for all schema creation

CREATE SCHEMA IF NOT EXISTS sa_online;
CREATE SCHEMA IF NOT EXISTS sa_offline;
CREATE SCHEMA IF NOT EXISTS bl_cl;
CREATE SCHEMA IF NOT EXISTS bl_3nf;
CREATE SCHEMA IF NOT EXISTS bl_dm;

COMMIT;
